[package]
name = "term-handler"
version = "0.1.0"
authors = ["Michael Micucci <michael.micucci@exchange.co.jp>"]

[dependencies]
lazy_static = "*"
signal = {git="http://git@github.com/kitsuneninetails/signal-rust"}
